# Rounded corners + shadows for i3
backend = "glx";
corner-radius = 10;
rounded-corners-exclude = [
  "class_g = 'i3-frame'"
];

# Shadows
shadow = true;
shadow-radius = 12;
shadow-opacity = 0.4;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-exclude = [
  "class_g = 'i3-frame'"
];

# Fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 3;

# Opacity
inactive-opacity-override = false;
active-opacity = 1;
inactive-opacity = 0.95;

# Window type settings
wintypes:
{
  normal = { };
  tooltip = { fade = true; shadow = false; opacity = 0.85; };
};
