# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  # Enable ntfs-3g FUSE mount helper for NTFS drives
  boot.supportedFilesystems = [ "ntfs-3g" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d2ea0714-ae4a-4da3-8426-0c64034538b9";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A0D3-3666";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/VM-Data" = {
    device = "/dev/disk/by-uuid/656A83285230348B";
    fsType = "ntfs-3g";
    options = [
      "uid=1000"
      "gid=100"
      "umask=022"
      "nofail"
      "x-systemd.device-timeout=30s"
      "windows_names"
    ];
  };

  fileSystems."/AI-Data" = {
    device = "/dev/disk/by-uuid/6F7C909300984928";
    fsType = "ntfs-3g";
    options = [
      "uid=1000"
      "gid=100"
      "umask=022"
      "nofail"
      "x-systemd.device-timeout=30s"
      "windows_names"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/bf1fbf51-d106-49eb-bef5-1be42929c111"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
